### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cheater7600** [ben-sb/javascript-deobfuscator#18]
/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:206
      throw this.createUnexpected(this.lookahead);
      ^

Error: [1:3561]: Unexpected identifier
    at new JsError (/root/javascript-deobfuscator/node_modules/shift-parser/dist/tokenizer.js:166:104)
    at GenericParser.createError (/root/javascript-deobfuscator/node_modules/shift-parser/dist/tokenizer.js:297:14)
    at GenericParser.createUnexpected (/root/javascript-deobfuscator/node_modules/shift-parser/dist/tokenizer.js:265:23)
    at GenericParser.expect (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:206:18)
    at GenericParser.parseGroupExpression (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:2215:12)
    at GenericParser.parsePrimaryExpression (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:1943:21)
    at GenericParser.parseLeftHandSideExpression (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:1779:21)
    at GenericParser.parseUpdateExpression (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:1656:26)
    at GenericParser.parseUnaryExpression (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:1628:21)
    at GenericParser.parseExponentiationExpression (/root/javascript-deobfuscator/node_modules/shift-parser/dist/parser.js:1598:23) {
  index: 3560,
  line: 1,
  column: 3561,
  parseErrorLine: 1,
  parseErrorColumn: 3561,
  description: 'Unexpected identifier'
}

**Comment by ben-sb** [comment]
Hi can you upload a sample that gets the error to Pastebin?
