### ISSUE TITLE
Replace proxy functions breaks on function that returns string literal

### ISSUE THREAD

**Issue by leumasme** [ben-sb/javascript-deobfuscator#31]
```js
function b() {
	return ':)';
}

b();
```

The above code fails to deobfuscate if the Replace Proxy Functions modification is used.
Tested both via Browser and npm package - fails at
```
Cannot read properties of undefined (reading 'expression')
at ProxyFunction.duplicateExpression (S:\Dev\javascript-deobfuscator\dist\modifications\proxies\proxyFunction.js:89:34)
    at ProxyFunction.getReplacement (S:\Dev\javascript-deobfuscator\dist\modifications\proxies\proxyFunction.js:35:31)
    at Controller.enter (S:\Dev\javascript-deobfuscator\dist\modifications\proxies\proxyRemover.js:205:61)
    at Controller.__execute (S:\Dev\javascript-deobfuscator\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (S:\Dev\javascript-deobfuscator\node_modules\estraverse\estraverse.js:501:28)
    at Object.traverse (S:\Dev\javascript-deobfuscator\node_modules\estraverse\estraverse.js:713:27)
    at ProxyRemover.replaceProxyFunctionUsages (S:\Dev\javascript-deobfuscator\dist\modifications\proxies\proxyRemover.js:190:20)
    at ProxyRemover.execute (S:\Dev\javascript-deobfuscator\dist\modifications\proxies\proxyRemover.js:38:14)
    at Object.deobfuscate (S:\Dev\javascript-deobfuscator\dist\index.js:74:22)
 ```

**Comment by ben-sb** [comment]
Should be fixed in e4332613ac47818c6cb227ec724a316b82e5676f
