### ISSUE TITLE
 Unexpected token "{"

### ISSUE THREAD

**Issue by 3052** [ben-sb/javascript-deobfuscator#47]
Uncaught Error: [3118:33]: Unexpected token "{"

https://github.com/ben-sb/javascript-deobfuscator/files/13258048/2.txt

**Comment by nisnevich** [comment]
Same here. Code sample to reproduce (https://deobfuscate.io/ fails either):

```
try {
    i(1), (o = !1);
} catch {
    o = !1;
}
```

Error stacktrace:

```
/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:206
      throw this.createUnexpected(this.lookahead);
      ^

Error: [1:10]: Unexpected token "{"
    at new JsError (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/tokenizer.js:166:104)
    at GenericParser.createError (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/tokenizer.js:297:14)
    at GenericParser.createUnexpected (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/tokenizer.js:276:23)
    at GenericParser.expect (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:206:18)
    at GenericParser.parseCatchClause (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:1094:12)
    at GenericParser.parseTryStatement (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:1048:32)
    at GenericParser.parseStatementHelper (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:663:23)
    at GenericParser.isolateCoverGrammar (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:1170:23)
    at GenericParser.parseStatement (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:627:23)
    at GenericParser.parseStatementListItem (/usr/local/lib/node_modules/js-deobfuscator/node_modules/shift-parser/dist/parser.js:620:23) {

```

**Comment by ben-sb** [comment]
This is due to the parser that is used not supported catch clauses without a parameter, unfortunately not much I can do about that without rewriting. If you change the third line to be `} catch (err) {` it should work.

**Comment by 3052** [comment]
just to confirm, you're basically saying you know the software doesn't work, but you are gonna leave it broken because its too hard to fix?

**Comment by ben-sb** [comment]
Turns out it was a simple fix, needed to upgrade the parser dependency. Also @3052 a pointer for the future, if you feel that any OS software is broken, feel free to contribute yourself and open a PR, much more productive than leaving comments like that 😃
