### ISSUE TITLE
throw new Error(`Ran out of variable names`)

### ISSUE THREAD

**Issue by idreamsoft** [ben-sb/javascript-deobfuscator#8]
/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:195
            throw new Error(`Ran out of variable names`);
            ^

Error: Ran out of variable names
    at VariableRenamer.getVariableName (/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:195:19)
    at VariableRenamer.renameVariables (/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:169:38)
    at VariableRenamer.renameVariables (/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:174:18)
    at VariableRenamer.renameVariables (/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:174:18)
    at VariableRenamer.renameVariables (/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:174:18)
    at VariableRenamer.execute (/tmp/javascript-deobfuscator/dist/modifications/renaming/variableRenamer.js:32:14)
    at /tmp/javascript-deobfuscator/dist/index.js:59:34
    at Array.forEach (<anonymous>)
    at Object.deobfuscate (/tmp/javascript-deobfuscator/dist/index.js:59:19)
    at Object.<anonymous> (/tmp/javascript-deobfuscator/dist/run.js:27:24)

**Comment by ben-sb** [comment]
Have added more variable names in https://github.com/ben-sb/javascript-deobfuscator/commit/25aebd71a5b67abbd951a801fa929f0bd25f2d4a
Let me know if that fixes it for you

**Comment by R3XET** [comment]
Hi! I've got this script and it give me this error when I try to deobfusate, I guess it's using an array obfuscation module.
Hastebin link: https://www.toptal.com/developers/hastebin/rawebozazi.md

[2022-01-20T08:08:12.372Z]: Executing FunctionExecutor
[2022-01-20T08:08:12.472Z]: Executing ProxyRemover
[2022-01-20T08:08:12.845Z]: Executing ExpressionSimplifier
[2022-01-20T08:08:12.876Z]: Executing ArrayUnpacker
[2022-01-20T08:08:12.956Z]: Executing ExpressionSimplifier
[2022-01-20T08:08:12.993Z]: Executing PropertySimplifier
[2022-01-20T08:08:13.264Z]: Executing VariableRenamer
C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:98
                                    throw new Error(`Identifier ${variable.name} has already been declared`);     
                                    ^

Error: Identifier _ has already been declared
    at Controller.enter (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:98:43)
    at Controller.__execute (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:501:28)
    at Object.traverse (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:713:27)
    at VariableRenamer.collectDeclarations (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:40:20)
    at VariableRenamer.execute (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:29:14)
    at Object.deobfuscate (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\index.js:61:22)
    at Object.<anonymous> (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\run.js:27:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
PS C:\Users\R3XET\Desktop\javascript-deobfuscator-master>

**Comment by ben-sb** [comment]
Hi, the sample provided seems to be too large for the website used (won't fully load for me at all), can you upload it to Pastebin?

**Comment by ben-sb** [comment]
> Hi! I've got this script and it gives me this error when I try to deobfuscate, I guess it's using an array obfuscation module. Hastebin link: https://www.toptal.com/developers/hastebin/rawebozazi.md
> 
> [2022-01-20T08:08:12.372Z]: Executing FunctionExecutor [2022-01-20T08:08:12.472Z]: Executing ProxyRemover [2022-01-20T08:08:12.845Z]: Executing ExpressionSimplifier [2022-01-20T08:08:12.876Z]: Executing ArrayUnpacker [2022-01-20T08:08:12.956Z]: Executing ExpressionSimplifier [2022-01-20T08:08:12.993Z]: Executing PropertySimplifier [2022-01-20T08:08:13.264Z]: Executing VariableRenamer C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:98 throw new Error(`Identifier ${variable.name} has already been declared`); ^
> 
> Error: Identifier _ has already been declared at Controller.enter (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:98:43) at Controller.__execute (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:397:31) at Controller.traverse (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:501:28) at Object.traverse (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:713:27) at VariableRenamer.collectDeclarations (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:40:20) at VariableRenamer.execute (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:29:14) at Object.deobfuscate (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\index.js:61:22) at Object. (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\run.js:27:24) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) PS C:\Users\R3XET\Desktop\javascript-deobfuscator-master>

.

**Comment by R3XET** [comment]
> > Hi! I've got this script and it gives me this error when I try to deobfuscate, I guess it's using an array obfuscation module. Hastebin link: https://www.toptal.com/developers/hastebin/rawebozazi.md
> > [2022-01-20T08:08:12.372Z]: Executing FunctionExecutor [2022-01-20T08:08:12.472Z]: Executing ProxyRemover [2022-01-20T08:08:12.845Z]: Executing ExpressionSimplifier [2022-01-20T08:08:12.876Z]: Executing ArrayUnpacker [2022-01-20T08:08:12.956Z]: Executing ExpressionSimplifier [2022-01-20T08:08:12.993Z]: Executing PropertySimplifier [2022-01-20T08:08:13.264Z]: Executing VariableRenamer C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:98 throw new Error(`Identifier ${variable.name} has already been declared`); ^
> > Error: Identifier _ has already been declared at Controller.enter (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:98:43) at Controller.__execute (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:397:31) at Controller.traverse (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:501:28) at Object.traverse (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\node_modules\estraverse\estraverse.js:713:27) at VariableRenamer.collectDeclarations (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:40:20) at VariableRenamer.execute (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\modifications\renaming\variableRenamer.js:29:14) at Object.deobfuscate (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\index.js:61:22) at Object. (C:\Users\R3XET\Desktop\javascript-deobfuscator-master\dist\run.js:27:24) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) PS C:\Users\R3XET\Desktop\javascript-deobfuscator-master>
> 
> .

Here you go! https://pastebin.com/9LXHK6DC

**Comment by ben-sb** [comment]
Should be fixed in 372ef7e8f8ba004c829068497fe7db0161a8d0e5
